# Generated by Django 4.2.9 on 2024-02-08 11:22

import apps.tasks.db_helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default=apps.tasks.db_helpers.generate_default_title,
                        max_length=75,
                        unique=True,
                        verbose_name="TASK NAME",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Здесь может быть ваше описание к задаче",
                        max_length=1000,
                        unique_for_date="date_started",
                    ),
                ),
                (
                    "date_started",
                    models.DateTimeField(
                        auto_now_add=True, help_text="ДАТА, КОГДА ЗАДАЧА БЫЛА СОЗДАНА"
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statuses.status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["date_started"],
                "get_latest_by": "date_started",
                "unique_together": {("category", "status", "description")},
            },
        ),
    ]
