# Generated by Django 4.2.9 on 2024-02-08 11:22

import apps.subtasks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
        ("categories", "0001_initial"),
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75)),
                (
                    "description",
                    models.TextField(blank=True, max_length=700, null=True),
                ),
                ("date_started", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(apps.subtasks.models.get_first_status),
                        to="statuses.status",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        limit_choices_to={"status": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubTask",
                "verbose_name_plural": "SubTasks",
            },
        ),
    ]
